### ISSUE TITLE
BFA experiance bar issues

### ISSUE THREAD

**Issue by Aideenwolf** [xmyno/oUF_Drk#4]
oUF 8.0.0
Exp 80000.24
oUF_Drk r30

Turning off the exp bar goes away turning it on gives the following error - not sure if this is oUF or the way the Exp bar is embedded. Posted here as well as in the Exp github just in case. :)

8x ...Ons\oUF_Drk\embeds\oUF_Experience\oUF_Experience.lua:162: Usage: <unnamed>:SetAlpha(alpha 0 to 1)
[C]: in function `SetAlpha'
...Ons\oUF_Drk\embeds\oUF_Experience\oUF_Experience.lua:162: in function <...Ons\oUF_Drk\embeds\oUF_Experience\oUF_Experience.lua:150>
...Ons\oUF_Drk\embeds\oUF_Experience\oUF_Experience.lua:195: in function <...Ons\oUF_Drk\embeds\oUF_Experience\oUF_Experience.lua:182>
(tail call): ?
oUF\ouf-8.0.0.lua:211: in function <oUF\ouf.lua:200>
(tail call): ?
[C]: in function `Show'
FrameXML\SecureStateDriver.lua:83: in function <FrameXML\SecureStateDriver.lua:73>
FrameXML\SecureStateDriver.lua:137: in function <FrameXML\SecureStateDriver.lua:119>

Locals:
(*temporary) = <unnamed> {
 __owner = oUF_DrkPlayerFrame {
 }
 ForceUpdate = <function> defined @oUF_Drk\embeds\oUF_Experience\oUF_Experience.lua:205
 restedAlpha = 0.15
 __accountMaxLevel = 110
 Text = <unnamed> {
 }
 Rested = <unnamed> {
 }
 0 = <userdata>
}
(*temporary) = nil

**Comment by xmyno** [comment]
I will investigate.

**Comment by xmyno** [comment]
Updated oUF_Experience with the bug fix of p3lim. Should be fine now.
