### ISSUE TITLE
Experience module

### ISSUE THREAD

**Issue by VaporAPX** [xmyno/oUF_Drk#5]
Hey bud, me again lol.  Just fired up a new lightforged draenai to start levelling and I get the following error.  

> 2x ...Ons\oUF_Drk\embeds\oUF_Experience\oUF_Experience.lua:162: Usage: <unnamed>:SetAlpha(alpha 0 to 1)
[C]: in function `SetAlpha'
...Ons\oUF_Drk\embeds\oUF_Experience\oUF_Experience.lua:162: in function <...Ons\oUF_Drk\embeds\oUF_Experience\oUF_Experience.lua:150>
...Ons\oUF_Drk\embeds\oUF_Experience\oUF_Experience.lua:195: in function <...Ons\oUF_Dr/g k\embeds\oUF_Experience\oUF_Experience.lua:182>
(tail call): ?
oUF\ouf-@project-version@.lua:211: in function <oUF\ouf.lua:200>
(tail call): ?
[C]: in function `Show'
FrameXML\SecureStateDriver.lua:83: in function <FrameXML\SecureStateDriver.lua:73>
FrameXML\SecureStateDriver.lua:137: in function <FrameXML\SecureStateDriver.lua:119>
Locals:
(*temporary) = <unnamed> {
 __owner = oUF_DrkPlayerFrame {
 }
 ForceUpdate = <function> defined @oUF_Drk\embeds\oUF_Experience\oUF_Experience.lua:205
 restedAlpha = 0.15
 __accountMaxLevel = 110
 Text = <unnamed> {
 }
 Rested = <unnamed> {
 }
 0 = <userdata>
}
(*temporary) = nil

I know the Experience module was causing some issues before so I'm sure it's related, but I thought I'd post regardless.  Thanks again for all the work on this.

**Comment by VaporAPX** [comment]
This error fires on Beta now too, which makes sense since the exp bar is live again passed 110.

**Comment by xmyno** [comment]
Are you on the latest version? If I understood the issue correctly this should have been solved by [this](https://github.com/xmyno/oUF_Drk/commit/92aa70c069e6684e8d5a6deaa89a60ca74086060#diff-5b550c4a029fb8c70cfdf761b219b5d6R162).

**Comment by VaporAPX** [comment]
Apparently I'm an idiot.  I read all about the change, but apparently didn't actually download the latest version.  My apologies, it's working fine with the newest update.  Sorry :(

**Comment by xmyno** [comment]
No worries, glad it's working.
